### ISSUE TITLE
Not able to login to my site after installing this plugin

### ISSUE THREAD

**Issue by Harshavardhanc** [clifgriffin/simple-ldap-login#41]
I installed this plugin to our wordpress blog site, after configuring this plugin I'm not able to login to my site getting http error 500. Any suggestions how to resolve this issue or how to remove the plugin so that I can reinstall it again.

**Comment by jpuck** [comment]
Do you have the extension `php-ldap` installed on your server? Do you have access to server logs?

**Comment by Harshavardhanc** [comment]
No php-ldap is not installed in the server. Yes I have the access to server logs.

**Comment by jpuck** [comment]
That's probably why you're getting errors, it must be installed. You should also check the error logs.

**Comment by Harshavardhanc** [comment]
How to disable this plugin in server? I'm using Ubuntu 14.04

**Comment by jpuck** [comment]
Should be opposite of installation steps. Deactivate it in admin console. Delete the files if you want.

**Comment by Harshavardhanc** [comment]
I'm not able to login to my admin wordpress console also. How to do it in server?

**Comment by Harshavardhanc** [comment]
Or how to disable it in server, any information of the path where the plugin is installed?

**Comment by clifgriffin** [comment]
@Harshavardhanc You can rename the plugin directory via FTP to disable.

**Comment by jpuck** [comment]
@Harshavardhanc the path should be `wp-content/plugins/simple-ldap-login`

**Comment by Harshavardhanc** [comment]
Thanks **@clifgriffin** Just need confirmation that renaming the directory wp-content/plugins/simple-ldap-login will disable the plugin?

**Comment by Harshavardhanc** [comment]
Thanks for the inputs @clifgriffin @jpuck renaming that directory worked!
