### ISSUE TITLE
[query] How are legacy Wordpress credentials migrated to LDAP?

### ISSUE THREAD

**Issue by kwill** [clifgriffin/simple-ldap-login#44]
Here's the scenario:
* We have legacy users using Wordpress-based authentication
* We want to migrate them to LDAP-based authentication, with minimal manual intervention. Something like:

If credentials not in LDAP  
And credentials in Wordpress  
Then re-create credentials in LDAP  
And login is successful

After installing simple-ldap-login, how do we get legacy users onto the LDAP database? Or is this not supported by this plugin?

**Comment by kwill** [comment]
Thanks for the feedback! In this case the legacy users don't have LDAP credentials. So we'd like to do something like: when legacy user logs in, remove Wordpress credentials and create LDAP credentials. Is that feasible?

**Comment by clifgriffin** [comment]
Ah, yeah that is not possible with this plugin. You'd need to contract out a project like that I think.
